// Auto-generated by Project X. Regenerate from profile JSON.

export const siteConfig = {
  businessName: 'King Of Kings Fence',
  tagline: 'Building trust with quality craftsmanship and integrity.',
  phone: '(469) 258-9458',
  phoneRaw: '14692589458',
  email: 'kingofkingsfence@gmail.com',
  address: '3415 Beall St, Dallas, TX 75223',
  googleMapsEmbedUrl: '',
  city: 'Dallas',
  state: 'Texas',
  serviceAreaNote: 'Serving the Dallas Metroplex — Richardson, Garland, Mesquite, Addison, Irving, Carrollton, and Farmers Branch.',
  establishedYear: null,
  heroTitle: 'Quality Fencing You Can Trust',
  heroSubtitle: 'Family-owned, faith-driven fence installation serving the Dallas Metroplex. Free quotes, honest pricing, and craftsmanship that lasts.',
  heroCta: 'Get a Free Quote',
  heroImageUrl: '',
  heroImageAlt: 'King Of Kings Fence professional fence installation',
  aboutHeadline: 'Why Dallas Homeowners Choose Us',
  aboutPoints: [
    {
      icon: 'Heart',
      title: 'Family-Owned & Faith-Based',
      description: 'Integrity is non-negotiable. We treat every home like our own.',
    },
    {
      icon: 'ShieldCheck',
      title: '200+ Projects Completed',
      description: 'Dallas-area homeowners trust King Of Kings Fence for quality that lasts.',
    },
    {
      icon: 'DollarSign',
      title: 'Free Quotes',
      description: 'No-pressure estimates with transparent pricing — no surprise costs.',
    }
  ],
  services: [
    {
      icon: 'Fence',
      title: 'Wood Fence Installation',
      description: 'Privacy and aesthetics with durable wood fencing built to last in Texas weather.',
      backgroundImage: 'https://images.unsplash.com/photo-1558618666-a8d05c42c219?w=600&q=80&auto=format&fit=crop',
      features: ['Privacy Fencing', 'Cedar & Pine Options', 'Stain & Seal Available', 'Free Quote'],
    },
    {
      icon: 'Shield',
      title: 'Wrought Iron Fence',
      description: 'Elegance, security, and style with expert wrought iron installation.',
      backgroundImage: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=600&q=80&auto=format&fit=crop',
      features: ['Custom Designs', 'Durability & Security', 'Professional Installation'],
    },
    {
      icon: 'Link',
      title: 'Chainlink Fence',
      description: 'Secure and practical chainlink fencing for residential and commercial properties.',
      backgroundImage: 'https://images.unsplash.com/photo-1631699462643-5c2e4d5ea649?w=600&q=80&auto=format&fit=crop',
      features: ['Affordable Option', 'Durable & Low Maintenance', 'Quick Installation'],
    },
    {
      icon: 'TreePine',
      title: 'Ranch Style Wood Fence',
      description: 'Rustic charm and aesthetic appeal for larger properties and rural settings.',
      backgroundImage: 'https://images.unsplash.com/photo-1500382017468-9049ed7dd88b?w=600&q=80&auto=format&fit=crop',
      features: ['Rustic Aesthetic', 'Durable Construction', 'Great for Large Properties'],
    },
    {
      icon: 'DoorOpen',
      title: 'Swing Gate Installation',
      description: 'Security, style, and seamless swing gate operation for residential entry.',
      backgroundImage: 'https://images.unsplash.com/photo-1558618666-a8d05c42c219?w=600&q=80&auto=format&fit=crop',
      features: ['Manual & Automated Options', 'Custom Sizing', 'Professional Install'],
    },
    {
      icon: 'ArrowRightLeft',
      title: 'Sliding Gate Installation',
      description: 'Convenience and smooth operation for automated driveway and property entry.',
      backgroundImage: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=600&q=80&auto=format&fit=crop',
      features: ['Motorized Options', 'Space-Efficient Design', 'Reliable Operation'],
    }
  ],
  pricingTiers: [
    {
      name: 'Free Quote',
      price: '0',
      description: 'On-site assessment and fencing consultation',
      features: ['Free quote', 'Property measurement', 'Material recommendations'],
      cta: 'Get a Quote',
      highlighted: false,
    },
    {
      name: 'Wood Fence',
      price: '25–45',
      priceUnit: '/ft',
      description: 'Classic privacy fencing with durable materials',
      features: ['Cedar & pine options', 'Stain & seal available', 'Built for Texas heat'],
      cta: 'Get a Quote',
      highlighted: true,
    },
    {
      name: 'Wrought Iron',
      price: '30–55',
      priceUnit: '/ft',
      description: 'Elegant security fencing with custom design options',
      features: ['Custom designs', 'Professional installation', 'Long-lasting finish'],
      cta: 'Get a Quote',
      highlighted: false,
    }
  ],
  reviews: [
    {
      name: 'Maria G.',
      location: 'Dallas',
      rating: 5,
      text: 'They built our privacy fence in under two days. Incredible quality and they cleaned up everything before they left.',
      avatar: 'MG',
    },
    {
      name: 'James R.',
      location: 'Richardson',
      rating: 5,
      text: 'Got a wrought iron fence for our front yard. Looks amazing and the price was fair. They were upfront about everything.',
      avatar: 'JR',
    },
    {
      name: 'Tracy L.',
      location: 'Garland',
      rating: 5,
      text: 'We needed a gate for our driveway and they delivered. Sliding gate works perfectly and the crew was respectful of our property.',
      avatar: 'TL',
    }
  ],
  googleReviewAvg: 5.0,
  googleReviewCount: 200,
  galleryImages: [
    {
      src: 'https://images.unsplash.com/photo-1558618666-a8d05c42c219?w=800&q=80&auto=format&fit=crop',
      alt: 'King Of Kings Fence wood fence installation',
    },
    {
      src: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&q=80&auto=format&fit=crop',
      alt: 'King Of Kings Fence wrought iron fencing',
    },
    {
      src: 'https://images.unsplash.com/photo-1500382017468-9049ed7dd88b?w=800&q=80&auto=format&fit=crop',
      alt: 'King Of Kings Fence ranch style fencing',
    }
  ],
  guaranteeHeadline: 'Our Quality Guarantee',
  guaranteeText: 'We use durable materials and expert installation techniques — and we stand behind every fence we build.',
  guaranteePoints: ['Free quotes before any work begins', 'Transparent, honest pricing', 'Craftsmanship built to last in Texas weather'],
  serviceOptions: ['Wood Fence', 'Wrought Iron Fence', 'Chainlink Fence', 'Ranch Style Fence', 'Swing Gate', 'Sliding Gate', 'Other'],
  formWebhookUrl: 'https://hooks.zapier.com/hooks/catch/26623925/uj1eyis/',
  formSource: 'kingofkingsfence',
  badges: ['Licensed & Insured', 'Free Quotes', '200+ Projects', 'Family-Owned'],
  footerYear: new Date().getFullYear(),
  footerLinks: {
    services: ['Wood Fence', 'Wrought Iron', 'Chainlink', 'Ranch Style', 'Swing Gate', 'Sliding Gate'],
    company: [
      { label: 'About Us', href: '#about' },
      { label: 'Our Guarantee', href: '#guarantee' },
      { label: 'Reviews', href: '#reviews' },
      { label: 'Gallery', href: '#gallery' },
      { label: 'Contact', href: '#contact' }
    ],
  },
  socialLinks: {
    facebook: 'https://www.facebook.com/reydereyeslandscaping/',
    instagram: '',
    google: 'https://www.yelp.com/biz/king-of-kings-fence-dallas-2',
  },
};

export type ServiceItem = (typeof siteConfig.services)[number];
export type ReviewItem = (typeof siteConfig.reviews)[number];
export type PricingTier = (typeof siteConfig.pricingTiers)[number];
export type GalleryImage = (typeof siteConfig.galleryImages)[number];