// Auto-generated by Project X. Regenerate from profile JSON.

export const siteConfig = {
  businessName: 'ClearDefense Pest Control',
  tagline: 'ClearDefense — The Clear Choice in Pest Control',
  phone: '(704) 879-2810',
  phoneRaw: '17048792810',
  email: '',
  address: '501 Penman Street, Suite 301, Charlotte, NC 28203',
  googleMapsEmbedUrl: '',
  city: 'Charlotte',
  state: 'North Carolina',
  serviceAreaNote: '31 locations across 13 states. Charlotte, NC is our local market.',
  establishedYear: null,
  heroTitle: 'Pest Control Done Right in Charlotte',
  heroSubtitle: 'Child and pet friendly. Pinpoint precision. 100% satisfaction guaranteed.',
  heroCta: 'Get a Free Quote',
  heroImageUrl: '',
  heroImageAlt: 'ClearDefense Pest Control professional service',
  aboutHeadline: 'Why Homeowners Trust Us',
  aboutPoints: [
    {
      icon: 'ShieldCheck',
      title: 'Pet & Child Safe',
      description: 'Our products are environmentally responsible and safe for your family.',
    },
    {
      icon: 'Clock',
      title: 'Quarterly Service',
      description: 'Text reminders, timely visits, and treatments that last longer between appointments.',
    },
    {
      icon: 'DollarSign',
      title: 'Free Quotes',
      description: 'No-pressure estimates with clear next steps before any treatment begins.',
    }
  ],
  services: [
    {
      icon: 'Bug',
      title: 'Pest Control',
      description: 'Quarterly pest control using environmentally responsible, pet-friendly products',
      backgroundImage: 'https://images.unsplash.com/photo-1589939705384-5185b7c7a30e?w=600&q=80&auto=format&fit=crop',
      features: ['Quarterly Service Visits', 'Text Reminders', 'Free Quotes', '100% Satisfaction Guarantee'],
    },
    {
      icon: 'Droplets',
      title: 'Mosquito Treatment',
      description: 'Targeted mosquito control for yards and outdoor living spaces',
      backgroundImage: 'https://images.unsplash.com/photo-1596462502278-279c7f1a0c6c?w=600&q=80&auto=format&fit=crop',
      features: ['Mosquito Treatment', 'Seasonal Protection'],
    },
    {
      icon: 'ShieldCheck',
      title: 'Termite Control',
      description: 'Termite inspection and treatment to protect your home from structural damage',
      backgroundImage: 'https://images.unsplash.com/photo-1558618666-a8d05c42c219?w=600&q=80&auto=format&fit=crop',
      features: ['Termite Inspection', 'Termite Treatment'],
    },
    {
      icon: 'BedDouble',
      title: 'Bed Bug Treatment',
      description: 'Emergency bed bug treatment — call immediately for fast response',
      backgroundImage: 'https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=600&q=80&auto=format&fit=crop',
      features: ['Bed Bug Treatment', 'Emergency Response'],
    }
  ],
  pricingTiers: [
    {
      name: 'Free Quote',
      price: '0',
      description: 'On-site assessment and pest inspection',
      features: ['Free quote', 'Pest identification', 'Recommended next steps'],
      cta: 'Get a Quote',
      highlighted: false,
    },
    {
      name: 'Quarterly Service',
      price: '149',
      description: 'Regular quarterly pest control visits',
      features: ['Quarterly treatments', 'Text reminders', 'Pet & child safe products'],
      cta: 'Schedule Service',
      highlighted: true,
    },
    {
      name: 'One-Time Treatment',
      price: 'Call',
      description: 'Single targeted treatment for specific pest issues',
      features: ['Targeted treatment', 'Same-week scheduling', 'Follow-up included'],
      cta: 'Call Now',
      highlighted: false,
    }
  ],
  reviews: [
    {
      name: 'ClearDefense Customer',
      location: 'Charlotte',
      rating: 5,
      text: 'Technicians are punctual and thorough. They text reminders before each visit.',
      avatar: 'CD',
    }
  ],
  googleReviewAvg: 5.0,
  googleReviewCount: 31,
  galleryImages: [
    {
      src: 'https://images.unsplash.com/photo-1589939705384-5185b7c7a30e?w=800&q=80&auto=format&fit=crop',
      alt: 'ClearDefense professional pest control service',
    },
    {
      src: 'https://images.unsplash.com/photo-1558618666-a8d05c42c219?w=800&q=80&auto=format&fit=crop',
      alt: 'ClearDefense home treatment',
    },
    {
      src: 'https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=800&q=80&auto=format&fit=crop',
      alt: 'ClearDefense residential service',
    }
  ],
  guaranteeHeadline: 'Our 100% Satisfaction Guarantee',
  guaranteeText: 'If something feels off between visits, ClearDefense comes back and makes it right — no extra charge.',
  guaranteePoints: ['Free quotes before any treatment begins', 'Pet and child safe products', '100% satisfaction guaranteed or we retreat for free'],
  serviceOptions: ['Pest Control', 'Mosquito Treatment', 'Termite Control', 'Bed Bug Treatment', 'Rodent Control', 'Other'],
  formWebhookUrl: 'https://hooks.zapier.com/hooks/catch/26623925/uj1eyis/',
  formSource: 'cleardefense',
  badges: ['Pet & Child Safe', 'Free Quotes', '31 Locations'],
  footerYear: new Date().getFullYear(),
  footerLinks: {
    services: ['Pest Control', 'Mosquito Treatment', 'Termite Control', 'Bed Bug Treatment'],
    company: [
      { label: 'About Us', href: '#about' },
      { label: 'Our Guarantee', href: '#guarantee' },
      { label: 'Reviews', href: '#reviews' },
      { label: 'Gallery', href: '#gallery' },
      { label: 'Contact', href: '#contact' }
    ],
  },
  socialLinks: {
    facebook: '',
    instagram: '',
    google: '',
  },
};

export type ServiceItem = (typeof siteConfig.services)[number];
export type ReviewItem = (typeof siteConfig.reviews)[number];
export type PricingTier = (typeof siteConfig.pricingTiers)[number];
export type GalleryImage = (typeof siteConfig.galleryImages)[number];